In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import sklearn.linear_model as lm
import pickle
from sklearn.externals import joblib

In [2]:
df=pd.read_csv("FuelConsumption.csv")
df.head()

,MODELYEAR,MAKE,MODEL,VEHICLECLASS,ENGINESIZE,CYLINDERS,TRANSMISSION,FUELTYPE,FUELCONSUMPTION_CITY,FUELCONSUMPTION_HWY,FUELCONSUMPTION_COMB,FUELCONSUMPTION_COMB_MPG,CO2EMISSIONS
0,2014,ACURA,ILX,COMPACT,2.0,4,AS5,Z,9.9,6.7,8.5,33,196
1,2014,ACURA,ILX,COMPACT,2.4,4,M6,Z,11.2,7.7,9.6,29,221
2,2014,ACURA,ILX HYBRID,COMPACT,1.5,4,AV7,Z,6.0,5.8,5.9,48,136
3,2014,ACURA,MDX 4WD,SUV - SMALL,3.5,6,AS6,Z,12.7,9.1,11.1,25,255
4,2014,ACURA,RDX AWD,SUV - SMALL,3.5,6,AS6,Z,12.1,8.7,10.6,27,244

In [3]:
df.describe()

,MODELYEAR,ENGINESIZE,CYLINDERS,FUELCONSUMPTION_CITY,FUELCONSUMPTION_HWY,FUELCONSUMPTION_COMB,FUELCONSUMPTION_COMB_MPG,CO2EMISSIONS
count,1067.0,1067.000000,1067.000000,1067.000000,1067.000000,1067.000000,1067.000000,1067.000000
mean,2014.0,3.346298,5.794752,13.296532,9.474602,11.580881,26.441425,256.228679
std,0.0,1.415895,1.797447,4.101253,2.794510,3.485595,7.468702,63.372304
min,2014.0,1.000000,3.000000,4.600000,4.900000,4.700000,11.000000,108.000000
25%,2014.0,2.000000,4.000000,10.250000,7.500000,9.000000,21.000000,207.000000
50%,2014.0,3.400000,6.000000,12.600000,8.800000,10.900000,26.000000,251.000000
75%,2014.0,4.300000,8.000000,15.550000,10.850000,13.350000,31.000000,294.000000
max,2014.0,8.400000,12.000000,30.200000,20.500000,25.800000,60.000000,488.000000

In [4]:
 value=np.random.rand(len(df))<.8

In [5]:
train=df[value]
test=df[~value]

In [6]:
regr=lm.LinearRegression()
train_x=np.asanyarray(train[["ENGINESIZE","CYLINDERS","FUELCONSUMPTION_COMB"]])
train_y=np.asanyarray(train[["CO2EMISSIONS"]])
regr.fit(train_x,train_y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [7]:
print(regr.coef_)

[[9.97300368 8.14838526 9.53894847]]

In [8]:
print(regr.intercept_)

[65.1621272]

In [9]:
joblib.dump(regr,"fuelconsumption_model2.pkl")

['fuelconsumption_model2.pkl']

In [10]:
test_x=np.asanyarray(test[["ENGINESIZE","CYLINDERS","FUELCONSUMPTION_COMB"]])
test_y=np.asanyarray(test[["CO2EMISSIONS"]])
prediction=regr.predict(test_x)
print(prediction)

[[198.78273759]
 [213.26478238]
 [254.84027966]
 [256.83488039]
 [317.44486909]
 [324.12213302]
 [213.09116029]
 [213.09116029]
 [250.80767266]
 [223.14472211]
 [224.09861695]
 [375.5341645 ]
 [311.5044724 ]
 [345.40540538]
 [345.40540538]
 [252.71546236]
 [262.25441082]
 [200.69052728]
 [181.61263035]
 [181.61263035]
 [200.69052728]
 [238.40703966]
 [239.3609345 ]
 [201.64442213]
 [219.32914272]
 [231.72977573]
 [295.37507105]
 [305.86791436]
 [204.50610667]
 [213.09116029]
 [248.89988297]
 [249.85377782]
 [306.82180921]
 [257.48493659]
 [259.39272628]
 [259.65315941]
 [307.34790175]
 [219.76842422]
 [208.53871367]
 [253.92979033]
 [214.04505514]
 [350.5283767 ]
 [333.35826946]
 [350.5283767 ]
 [250.11421095]
 [193.92645231]
 [312.11737599]
 [398.78636419]
 [349.9206994 ]
 [370.47335744]
 [204.67972876]
 [183.25998691]
 [191.06476777]
 [183.25998691]
 [190.89114569]
 [314.84361768]
 [358.72278063]
 [248.20642125]
 [287.31610997]
 [217.08036177]
 [287.31610997]
 [315.01723976]
 [248.20642125]
 [287.31610997]
 [309.29387068]
 [325.81392173]
 [253.92979033]
 [199.73663244]
 [209.44920299]
 [181.35219722]
 [298.76284813]
 [268.23821303]
 [176.58272299]
 [186.12167145]
 [211.1833706 ]
 [267.32772371]
 [390.24471609]
 [343.85111277]
 [368.13151253]
 [368.13151253]
 [170.68573182]
 [214.04505514]
 [301.35887326]
 [204.33248459]
 [300.97447648]
 [340.59877854]
 [349.9206994 ]
 [370.47335744]
 [304.35077436]
 [344.41435793]
 [277.12710531]
 [348.22993731]
 [208.49530814]
 [358.72278063]
 [240.53185696]
 [211.35699268]
 [178.5339182 ]
 [184.25728728]
 [276.77986113]
 [257.83218076]
 [227.39958299]
 [209.27558091]
 [180.83235759]
 [214.04505514]
 [190.02406188]
 [253.97319585]
 [255.88098555]
 [273.05109279]
 [245.08430358]
 [260.34662113]
 [262.25441082]
 [307.08224234]
 [262.25441082]
 [307.08224234]
 [305.17445264]
 [300.40497841]
 [212.31088753]
 [218.03425661]
 [250.89448371]
 [265.37652849]
 [344.89181866]
 [218.98815146]
 [198.78273759]
 [186.2084825 ]
 [259.52294285]
 [198.6091155 ]
 [199.56301035]
 [201.64442213]
 [364.48330232]
 [211.1833706 ]
 [262.25441082]
 [323.29845473]
 [261.30051598]
 [324.25234958]
 [231.51274812]
 [250.07080542]
 [253.88638481]
 [300.40497841]
 [293.5540924 ]
 [288.95824025]
 [254.84027966]
 [323.16823817]
 [194.01326336]
 [271.1433031 ]
 [193.27639612]
 [192.32250127]
 [199.95366005]
 [209.27558091]
 [212.13726545]
 [194.01326336]
 [282.50323021]
 [358.80959167]
 [301.58112715]
 [312.67539485]
 [200.60371624]
 [188.11627219]
 [188.11627219]
 [183.34679796]
 [196.70132581]
 [188.11627219]
 [190.02406188]
 [194.79353612]
 [192.88574642]
 [190.02406188]
 [192.88574642]
 [190.02406188]
 [199.56301035]
 [192.88574642]
 [194.79353612]
 [192.88574642]
 [190.02406188]
 [241.2687242 ]
 [260.65045978]
 [262.55824948]
 [240.01724361]
 [261.51754359]
 [190.11087293]
 [176.66953403]
 [284.62804752]
 [250.0273999 ]
 [256.87828592]
 [253.06270653]
 [255.92439107]
 [228.73787462]
 [247.16571536]
 [302.22595706]
 [308.90322099]
 [235.41513855]
 [255.83758003]
 [321.69450369]
 [319.74853476]
 [258.69926457]
 [381.38775015]
 [392.87789383]
 [208.53871367]
 [209.27558091]
 [208.53871367]
 [274.91547696]
 [205.46000152]
 [286.53583721]
 [255.7941745 ]
 [227.1773291 ]
 [168.17129145]
 [346.49576971]
 [278.90467843]
 [238.19626496]
 [287.48973206]
 [221.98005256]
 [182.34949759]
 [196.78813685]
 [224.3182577 ]
 [207.36779121]
 [227.17994224]
 [209.27558091]
 [253.6693572 ]
 [253.75616825]]